# Generated by Django 3.0.1 on 2019-12-21 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeMan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3.9, max_digits=2),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='time_placed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
