# Generated by Django 3.0.1 on 2019-12-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeMan', '0003_auto_20191222_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3.5, max_digits=2),
        ),
    ]
