# Generated by Django 3.0.1 on 2019-12-21 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafeMan', '0004_auto_20191222_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3.6, max_digits=2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
