# Generated by Django 3.0.1 on 2019-12-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeMan', '0007_auto_20191222_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='etp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='otp',
            field=models.CharField(max_length=100),
        ),
    ]
