# Generated by Django 3.0.1 on 2019-12-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeMan', '0008_auto_20191222_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3.8, max_digits=2),
        ),
    ]
